# Generated by Django 3.1.4 on 2021-01-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component_description',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=25)),
                ('component_lk_number', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation_data',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift_description',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_code', models.CharField(max_length=5)),
                ('shift_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine_data',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_number', models.CharField(max_length=12)),
                ('machine_description', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('operation_id', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_master_app.operation_data')),
            ],
        ),
        migrations.CreateModel(
            name='Laser_production_data',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=10)),
                ('component_lot_number', models.CharField(max_length=5)),
                ('component_quantity', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('component_id', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_master_app.component_description')),
                ('machine_id', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_master_app.machine_data')),
                ('shift_id', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_master_app.shift_description')),
            ],
        ),
    ]
